import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{backgroundColor: "lightgray", padding: "10px"}}>
          <h1>Header</h1>
        </header>
        {children}
        <footer style={{backgroundColor: "ghostwhite", padding: "10px"}}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
}
//app level layout